#!/usr/bin/env bash
#
# run.sh — Test gwas2cojo.py against four datasets of increasing complexity.
#
# Usage:
#   cd test/
#   bash run.sh
#
# Outputs are written to /tmp/gwas2cojo_test_*.  The three synthetic datasets
# (gwas_metal_tab, gwas_plink2, gwas_saige) are generated by generate_test_data.py
# and committed to the repository so no pre-generation step is needed.
#
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

cd "$(dirname "$0")"

GEN="$(cd ..; pwd)/gwas2cojo.py"
VER="$(cd ..; pwd)/gwas2cojo-verify.py"
OUT="/tmp/gwas2cojo_test"

SEP() { printf '\n%s\n' '──────────────────────────────────────────────────────────'; }
HDR() { SEP; echo "  $*"; SEP; }

# ── Test 0: Minimal smoke test (A.txt / B.txt, 1 variant each) ───────────────
HDR "Test 0 — Minimal smoke test  (A.txt / B.txt)"

python3 "$GEN" \
    --gen        A.txt \
    --gen:ident  ident  --gen:effect effect --gen:other other --gen:eaf eaf \
    --gwas       B.txt \
    --gwas:build hg19 \
    -o           "${OUT}_0.cojo" \
    --output-pos | grep -v '^+'

echo
echo "  Genetic reference (A.txt):"
column -t A.txt | sed 's/^/    /'
echo
echo "  GWAS to align (B.txt):"
column -t B.txt | sed 's/^/    /'
echo
echo "  Output (${OUT}_0.cojo):"
column -t "${OUT}_0.cojo" | sed 's/^/    /'

# ── Test 1: METAL-style  (all columns auto-detected) ─────────────────────────
#
#   Header: MarkerName CHR BP Allele1 Allele2 Freq1 Effect StdErr P-value N
#   ~15 % of variants on complement strand → tests translated-allele matching.
#   Uses --report-ok so gwas2cojo-verify.py can validate the beta/freq transforms.
#
HDR "Test 1 — METAL-style  gwas_metal_tab.txt.gz  (auto-detect all columns)"

python3 "$GEN" \
    --gen        ref.txt.gz \
    --gen:ident  id  --gen:effect a1  --gen:other a2  --gen:eaf eaf \
    --gwas       gwas_metal_tab.txt.gz \
    --gwas:build hg19 \
    --report-ok \
    -o           "${OUT}_1.cojo" \
    -r           "${OUT}_1.report" \
    --output-pos 2>&1 | grep -v '^+'

echo
echo "  Verifying allele/beta transforms (gwas2cojo-verify.py) …"
python3 "$VER" "${OUT}_1.report"

# ── Test 2: PLINK2-style  (A1FREQ and OBS_CT alias auto-detection) ────────────
#
#   Header: CHR POS ID A1 A2 A1FREQ BETA SE P OBS_CT
#   A1FREQ → GWAS_H_FREQ_OPTIONS  (added v1.4.4)
#   OBS_CT → GWAS_H_NTOTAL_OPTIONS (added v1.4.4)
#   ~20 % of variants switched (A1 = non-effect) → tests ACT_FLIP branch.
#
HDR "Test 2 — PLINK2-style  gwas_plink2.txt.gz  (A1FREQ + OBS_CT alias auto-detect)"

python3 "$GEN" \
    --gen        ref.txt.gz \
    --gen:ident  id  --gen:effect a1  --gen:other a2  --gen:eaf eaf \
    --gwas       gwas_plink2.txt.gz \
    --gwas:build hg19 \
    -o           "${OUT}_2.cojo" \
    -r           "${OUT}_2.report" \
    --output-pos 2>&1 | grep -v '^+'

# ── Test 3: SAIGE-style  (manual --gwas:effect / --gwas:other / --gwas:freq) ──
#
#   Header: CHR POS SNPID Allele1 Allele2 AF_Allele2 BETA SE p.value N
#   SAIGE convention: Allele1 = non-effect, Allele2 = effect.
#   AF_Allele2 is the effect-allele frequency.
#   Manual overrides are required because the default detection expects
#   Allele1 to be the effect allele (METAL convention).
#
HDR "Test 3 — SAIGE-style  gwas_saige.txt.gz  (manual column overrides)"

python3 "$GEN" \
    --gen          ref.txt.gz \
    --gen:ident    id  --gen:effect a1  --gen:other a2  --gen:eaf eaf \
    --gwas         gwas_saige.txt.gz \
    --gwas:build   hg19 \
    --gwas:effect  Allele2 \
    --gwas:other   Allele1 \
    --gwas:freq    AF_Allele2 \
    -o             "${OUT}_3.cojo" \
    -r             "${OUT}_3.report" \
    --output-pos 2>&1 | grep -v '^+'

# ── Summary ───────────────────────────────────────────────────────────────────
SEP
echo "  All tests completed successfully."
printf '  %-40s  %s\n' "Output" "Location"
printf '  %-40s  %s\n' "------" "--------"
for i in 0 1 2 3; do
    if [[ -f "${OUT}_${i}.cojo" ]]; then
        n=$(wc -l < "${OUT}_${i}.cojo")
        printf '  %-40s  %d lines\n' "${OUT}_${i}.cojo" "$((n - 1))"
    fi
done
SEP
