#!/usr/bin/env bash
#SBATCH --job-name=fix_migraine_choquet
#SBATCH --output=fix_migraine_choquet_%j.out
#SBATCH --error=fix_migraine_choquet_%j.err
#SBATCH --time=01:00:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=1

# Choquet2021 Migraine PAN — extract relevant columns from the harmonised GWAS Catalog
# file (GRCh38).  The previous parsed file was generated by a buggy pipeline that
# duplicated/appended extra columns to each data row, causing a preprocess Traceback.
# This script regenerates a clean parsed file from the authoritative .h.tsv.gz source.
#
# standard_error is NA throughout and no CI columns exist.  SE derivation strategies
# 1 and 2 in harmonia.py both fail.  Strategy 4 (harmonia.py v1.4.51) handles
# this case: when only OR + P are present it derives beta = ln(OR) internally, then
# back-calculates SE = |beta|/|Z|.  odds_ratio is therefore passed through as-is.
# effect_allele_frequency is NA throughout; --fill-eaf covers it downstream.
# rsid is the last column in the source and is affected by CRLF line endings;
# it is dropped here (harmonia.py re-assigns rsIDs via --dbsnp).
# gsub(/\r/, ...) strips CRLF so the last real column parses correctly.
#
# Source columns used (9 output columns):
#   variant_id              → variant_id   (first; rsID from source variant_id field)
#   chromosome              → chromosome
#   base_pair_location      → base_pair_location  (GRCh38/hg38 — harmonised)
#   effect_allele           → effect_allele
#   other_allele            → other_allele
#   odds_ratio              → odds_ratio
#   standard_error          → standard_error  (NA throughout; dropped by strategy 4)
#   effect_allele_frequency → effect_allele_frequency  (NA throughout; --fill-eaf)
#   p_value                 → p_value
#   (hm_coordinate_conversion, hm_code, rsid dropped — metadata / CRLF issue)

set -euo pipefail

INDIR="/hpc/dhl_ec/data/_gwas_datasets/_Migraine/Choquet2021/harmonised"

f="GCST90000016.h.tsv.gz"
in="${INDIR}/${f}"
out="${INDIR}/${f/.h.tsv.gz/.parsed.txt.gz}"

if [[ ! -f "${in}" ]]; then
    echo "ERROR: input file not found: ${in}" >&2
    exit 1
fi

echo "→ ${f}"
zcat "${in}" | awk 'BEGIN{FS=OFS="\t"}
NR==1 {
    for(i=1;i<=NF;i++) { gsub(/\r/, "", $i); h[$i]=i }
    print "variant_id","chromosome","base_pair_location",\
          "effect_allele","other_allele",\
          "odds_ratio","standard_error","effect_allele_frequency",\
          "p_value"
    next
}
{
    gsub(/\r$/, "")
    print $h["variant_id"],$h["chromosome"],$h["base_pair_location"],\
          $h["effect_allele"],$h["other_allele"],\
          $h["odds_ratio"],$h["standard_error"],$h["effect_allele_frequency"],\
          $h["p_value"]
}' | gzip > "${out}"
echo "   Lines: $(zcat "${out}" | wc -l)"
