#!/usr/bin/env bash
#SBATCH --job-name=fix_t1d_mcgrail
#SBATCH --output=fix_t1d_mcgrail_%j.out
#SBATCH --error=fix_t1d_mcgrail_%j.err
#SBATCH --time=02:00:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=1

# McGrail2026 T1D — extract relevant columns from the harmonised GWAS Catalog file.
# The previous parsed file (GCST90824163.parsed.txt.gz) was generated by a buggy
# pipeline that duplicated/appended extra columns to each data row, causing a
# preprocess Traceback.  Running this script regenerates a clean parsed file.
# Original has 13 columns; keeping 10 key columns.
# variant_id is the last column and is affected by CRLF line endings (stored as
# "variant_id\r" in the awk hash → $h["variant_id"]=0 → $0 printed for that field).
# It is dropped here; hm_coordinate_conversion and hm_code also dropped (metadata).
# gsub(/\r/, ...) strips CRLF so the last real column parses correctly.
#
# Source columns used (10 output columns):
#   rsid                    → rsid          (first)
#   chromosome              → chromosome    (GRCh38/hg38 — harmonised)
#   base_pair_location      → base_pair_location
#   effect_allele           → effect_allele
#   other_allele            → other_allele
#   beta                    → beta
#   standard_error          → standard_error
#   effect_allele_frequency → effect_allele_frequency
#   p_value                 → p_value
#   n                       → n
#   (variant_id, hm_coordinate_conversion, hm_code dropped)

set -euo pipefail

INDIR="/hpc/dhl_ec/data/_gwas_datasets/_DIABETES/T1D/mcgrail_2026/harmonised"

f="GCST90824163.h.tsv.gz"
in="${INDIR}/${f}"
out="${INDIR}/${f/.h.tsv.gz/.parsed.txt.gz}"

if [[ ! -f "${in}" ]]; then
    echo "ERROR: input file not found: ${in}" >&2
    exit 1
fi

echo "→ ${f}"
zcat "${in}" | awk 'BEGIN{FS=OFS="\t"}
NR==1 {
    for(i=1;i<=NF;i++) { gsub(/\r/, "", $i); h[$i]=i }
    print "rsid","chromosome","base_pair_location",\
          "effect_allele","other_allele",\
          "beta","standard_error","effect_allele_frequency",\
          "p_value","n"
    next
}
{
    gsub(/\r$/, "")
    print $h["rsid"],$h["chromosome"],$h["base_pair_location"],\
          $h["effect_allele"],$h["other_allele"],\
          $h["beta"],$h["standard_error"],$h["effect_allele_frequency"],\
          $h["p_value"],$h["n"]
}' | gzip > "${out}"
echo "   Lines: $(zcat "${out}" | wc -l)"
